[package]
name = "tskit"
version = "0.1.2"
authors = ["molpopgen <krthornt@uci.edu>"]
build = "build.rs"
edition = "2018"
description = "rust interface to tskit"
license = "MIT"
homepage = "https://github.com/molpopgen/tskit_rust"
repository = "https://github.com/molpopgen/tskit_rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
libc = "0.2.81"
streaming-iterator = "0.1.5"
bitflags = "1.2.1"

[dev-dependencies]
clap = "~2.27.0"
serde = {version = "1.0.118", features = ["derive"]}
bincode = "1.3.1"
rand = "0.8.3"
rand_distr = "0.4.0"

[build-dependencies]
bindgen = "0.57.0"
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"

[[example]]
name = "mutation_metadata_bincode"

[[example]]
name = "mutation_metadata_std"

# Not run during tests
[[example]]
name = "tree_traversals"

[[example]]
name = "forward_simulation"
