[package]
name = "tskit"
version = "0.3.0"
authors = ["tskit developers <admin@tskit.dev>"]
build = "build.rs"
edition = "2018"
description = "rust interface to tskit"
license = "MIT"
homepage = "https://github.com/tskit-dev/tskit-rust"
repository = "https://github.com/tskit-dev/tskit-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units=1

[dependencies]
thiserror = "1.0"
libc = "0.2.81"
streaming-iterator = "0.1.5"
bitflags = "1.2.1"
chrono = {version = "0.4.19", optional = true}

[dev-dependencies]
clap = "~2.33.3"
serde = {version = "1.0.118", features = ["derive"]}
bincode = "1.3.1"
rand = "0.8.3"
rand_distr = "0.4.0"

[build-dependencies]
bindgen = "0.59.1"
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"

[features]
provenance = ["chrono"]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "mutation_metadata_bincode"

[[example]]
name = "mutation_metadata_std"

# Not run during tests
[[example]]
name = "tree_traversals"

[[example]]
name = "forward_simulation"
