name: github pages

on:
  push:
    branches:
      - main
  release:
    types: [created]
  pull_request:

jobs:
  mdbook:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2.0.0
        with:
          mdbook-version: 'latest'

      - run: mdbook build book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: github.event_name == 'release'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
