name: Security audit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4.2.2
      
      - name: Perform the security audit
        uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
